SELECT
    PRDPLATE.PRD_PART_OID AS PARTOID,
    STDMAT.CODE AS MATERIAL,
    PRDPLATE.MATERIAL_OID AS MATERIAL_OID,
    PRDPLATE.THICKNESS AS THICK,
    (SELECT STORAGE_CODE FROM STD_PLATE WHERE THICKNESS = PRDPLATE.THICKNESS AND MATERIAL_OID = PRDPLATE.MATERIAL_OID) AS STOCK_CODE
FROM
    PRD_PLATE_ATT PRDPLATE,
    MATERIAL STDMAT
WHERE
    PRDPLATE.PRD_PART_OID IN (&plateOids) AND
    PRDPLATE.MATERIAL_OID = STDMAT.OID
UNION ALL
SELECT
    INPPLATE.INP_PART_OID AS PARTOID,
    STDMAT.CODE AS MATERIAL,
    INPPLATE.MATERIAL_OID AS MATERIAL_OID,
    INPPLATE.THICKNESS * 1000 AS THICK,
    (SELECT STORAGE_CODE FROM STD_PLATE WHERE THICKNESS = INPPLATE.THICKNESS * 1000 AND MATERIAL_OID = INPPLATE.MATERIAL_OID) AS STOCK_CODE
FROM
    INP_PLATE_ATT_DB INPPLATE,
    MATERIAL STDMAT
WHERE
    INPPLATE.INP_PART_OID IN (&plateOids) AND
    INPPLATE.MATERIAL_OID = STDMAT.OID
UNION ALL
SELECT
    ASPLATE.OID AS PARTOID,
    ASPLATE.MATQ AS MATERIAL,
    MATT.OID AS MATERIAL_OID,
    ASPLATE.THICKNESS AS THICK,
    (SELECT STORAGE_CODE FROM STD_PLATE WHERE THICKNESS = ASPLATE.THICKNESS AND MATERIAL_OID = MATT.OID) AS STOCK_CODE
FROM
    AS_STD_PART_PLATE ASPLATE,
    MATERIAL MATT
WHERE
    ASPLATE.OID IN (&plateOids) AND
    MATT.CODE = ASPLATE.MATQ
UNION ALL
SELECT
    ASCONTPLATE.OID AS PARTOID,
    ASCONTPLATE.MATQ AS MATERIAL,
    MATT.OID AS MATERIAL_OID,
    ASCONTPLATE.THICKNESS AS THICK,
    (SELECT STORAGE_CODE FROM STD_PLATE WHERE THICKNESS = ROUND(ASCONTPLATE.THICKNESS) AND MATERIAL_OID = MATT.OID) AS STOCK_CODE
FROM
    AS_PART_CONT_PLATE ASCONTPLATE,
    MATERIAL MATT
WHERE
    ASCONTPLATE.OID IN (&plateOids) AND
    MATT.CODE = ASCONTPLATE.MATQ