SELECT
    STDPROF.OID as KSE,
    STDPROF.SECTION as PROF_SECTION,
    STDPROF.WEB_HEIGHT as WEB_HEIGHT,
    STDPROF.WEB_THICKNESS as WEB_THICKNESS,
    STDPROF.FLANGE_HEIGHT as FLANGE_HEIGHT,
    STDPROF.FLANGE_THICKNESS as FLANGE_THICKNESS,
    STDPROF.MATERIAL_OID AS MATERIAL_OID,
    STDMAT.CODE as MATERIAL,
    STDPROF.STOCK_CODE0 as STOCK_CODE
FROM
    STD_PROFILE STDPROF,
    MATERIAL STDMAT
WHERE
    STDPROF.OID IN (&profileKse) AND
    STDPROF.MATERIAL_OID = STDMAT.OID