SELECT *
FROM
    (
        SELECT
            CODE,
            BLOCK,
            DESCRIPTION,
            WEIGHT,
            (SELECT WEB_THICKNESS FROM STD_PROFILE WHERE KSE = GKSE) AS THICKNESS,
            (SELECT CODE FROM MATERIAL WHERE OID =(SELECT MATERIAL_OID FROM STD_PROFILE WHERE KSE = GKSE)) AS MATERIAL
        FROM
            (SELECT
                 P.CODE AS CODE,
                 (SELECT CODE FROM BLOCK WHERE OID = P.BLOCK_OID) AS BLOCK,
                 P.DESCRIPTION AS DESCRIPTION,
                 PEP.WEIGHT AS WEIGHT,
                 (
                     SELECT STD.kse AS KSE FROM STD_PROFILE STD, PRD_PROFILE PRF WHERE STD.OID=PRF.STD_PROFILE_OID AND PRF.PRD_PART_OID = P.OID AND STD.SECTION = 0
                     UNION ALL
                     SELECT STD.kse AS KSE FROM STD_PROFILE STD, INP_PROFILE_ATT_DB PRF WHERE STD.OID=PRF.STD_PROFILE_OID AND PRF.INP_PART_OID = P.OID AND STD.SECTION = 0
                     UNION ALL
                     SELECT STD.kse AS KSE FROM STD_PROFILE STD, INP_LC_ATT_DB PRF WHERE STD.OID=PRF.STD_SECTION_OID AND PRF.INP_PART_OID = P.OID AND STD.SECTION = 0
                     UNION ALL
                     SELECT STD.kse AS KSE FROM STD_PROFILE STD, AS_STD_PART_PROF PRF WHERE STD.KSE=PRF.KSE AND PRF.OID=P.OID  AND STD.SECTION = 0
                 ) AS GKSE
             FROM
                 PRD_PART P, PRD_EXPL_PART PEP
             WHERE
                     P.PART_TYPE IN (17, 19, 24, 21) AND
                     P.BLOCK_OID NOT IN (SELECT OID FROM BLOCK WHERE CODE LIKE 'L%') AND
                     PEP.PRD_PART_OID = P.OID)
        WHERE
                GKSE IS NOT NULL
        UNION ALL
        SELECT
            P.CODE,
            (SELECT CODE FROM BLOCK WHERE OID = P.BLOCK_OID) AS BLOCK,
            CASE WHEN P.DESCRIPTION IS NULL THEN 'Aux Plate' ELSE P.DESCRIPTION END AS DESCRIPTION,
            PEP.WEIGHT,
            (
                SELECT THICKNESS AS THK FROM PRD_PLATE_ATT WHERE PRD_PART_OID = P.OID
                UNION ALL
                SELECT THICKNESS AS THK FROM SHDK_STD_PLATE WHERE PRD_PART_OID = P.OID
                UNION ALL
                SELECT THICKNESS * 1000 AS THK FROM INP_PLATE_ATT_DB WHERE INP_PART_OID = P.OID
                UNION ALL
                SELECT THICKNESS AS THK FROM AS_STD_PART_PLATE WHERE OID = P.OID
            ) AS THICKNESS,
            (
                SELECT CODE AS MAT FROM MATERIAL WHERE OID = (SELECT MATERIAL_OID FROM PRD_PLATE_ATT WHERE PRD_PART_OID = P.OID)
                UNION ALL
                SELECT CODE AS MAT FROM MATERIAL WHERE OID = (SELECT MATERIAL_OID FROM SHDK_STD_PLATE WHERE PRD_PART_OID = P.OID)
                UNION ALL
                SELECT CODE AS MAT FROM MATERIAL WHERE OID = (SELECT MATERIAL_OID FROM INP_PLATE_ATT_DB WHERE INP_PART_OID = P.OID)
                UNION ALL
                SELECT MATQ AS MAT FROM AS_STD_PART_PLATE
                WHERE OID = P.OID
            ) AS MAT
        FROM
            PRD_PART P, PRD_EXPL_PART PEP
        WHERE
                P.PART_TYPE IN (8, 9, 10, 11, 12, 13, 14, 15, 18, 20, 22, 23, 25, 26, 31, 16)
          AND P.BLOCK_OID NOT IN (SELECT OID FROM BLOCK WHERE CODE LIKE 'L%')
          AND PEP.PRD_PART_OID = P.OID
    )
WHERE THICKNESS = &thickness AND MATERIAL = '&material'