select
    PP_OID,
    EXPL_OID,
    BLOCK,
    CODE,
    PART_TYPE,
    DESCRIPTION,
    PARENT_NODE,
    ATOM_TYPE,
    ORDINAL,
    TYPE_ATOM_TYPE,
    SYMBOL,
    WEIGHT,
    X_COG,
    Y_COG,
    Z_COG,
    PRF_LENGTH,
    LINE_NAME,
    LINE_TYPE,
    LINE_TYPE_DESCRIPTION,
    BS_ADN,
    GET_KSE_KPL(PP_OID,EXPL_OID, PART_TYPE, 0) as KSE,
    (
    select     PATT.THICKNESS*1000   from PRD_PART PP , INP_PLATE_ATT_DB IPLA, INP_PLATE_ATT_DB PATT , STD_PLATE SPL  WHERE
    PP.oid= PP_OID
    AND PP.PART_TYPE IN (14,15,18,20,22,23,25,26)
    AND IPLA.INP_PART_OID = PP.OID
    AND PATT.INP_PART_OID=PP.OID
    AND (SPL.MATERIAL_OID=PATT.MATERIAL_OID
    AND SPL.THICKNESS=PATT.THICKNESS*1000)
    union all
    select     PL.THICKNESS  from PRD_PART PP ,SHDK_PLATE PL, V_RPT_SHDK_PLATE_ATT ATT, STD_PLATE SPL   WHERE
    PP.oid= PP_OID
    AND   PP.PART_TYPE IN (9, 10)
    AND PL.PRD_PART_OID=PP.oid
    AND ATT.PRD_PART_OID=PP.oid
    AND (SPL.MATERIAL_OID=ATT.MATERIAL_OID
    AND SPL.THICKNESS=PL.THICKNESS)
    union all
    select    IPRA.PL_THICK_VALUE*1000   from PRD_PART PP, INP_LC_ATT_DB IPRA ,STD_PROFILE PROF, STD_PLATE SPL  WHERE
    PP.oid= PP_OID
    AND  PP.PART_TYPE IN (17)
    AND IPRA.INP_PART_OID = PP.OID
    AND PROF.OID=IPRA.STD_SECTION_OID
    AND (SPL.MATERIAL_OID=PROF.MATERIAL_OID
    AND SPL.THICKNESS=IPRA.PL_THICK_VALUE*1000)
    )      as thick,
    (
    select  SPL.STORAGE_CODE   from PRD_PART PP , INP_PLATE_ATT_DB IPLA, INP_PLATE_ATT_DB PATT , STD_PLATE SPL   WHERE
    PP.oid= PP_OID
    AND   PP.PART_TYPE IN (14,15,18,20,22,23,25,26)
    AND IPLA.INP_PART_OID = PP.OID
    AND PATT.INP_PART_OID=PP.OID
    AND (SPL.MATERIAL_OID=PATT.MATERIAL_OID AND SPL.THICKNESS=PATT.THICKNESS*1000)
    union all
    select  STD.STOCK_CODE0                from PRD_PART PP , PRD_PROFILE PRF, STD_PROFILE STD  WHERE
    PP.oid= PP_OID
    AND PP.PART_TYPE IN (0,1,2,3,6)
    AND PRF.PRD_PART_OID = PP.OID
    AND PRF.STD_PROFILE_OID=STD.OID
    union all
    select SPL.STORAGE_CODE  from PRD_PART PP ,SHDK_PLATE PL, V_RPT_SHDK_PLATE_ATT ATT, STD_PLATE SPL  WHERE
    PP.oid= PP_OID
    AND  PP.PART_TYPE IN (9, 10)
    AND PL.PRD_PART_OID=PP.oid
    AND ATT.PRD_PART_OID=PP.oid
    AND (SPL.MATERIAL_OID=ATT.MATERIAL_OID AND SPL.THICKNESS=PL.THICKNESS)
    union all
    select   STD.STOCK_CODE0      from PRD_PART PP , INP_PROFILE_ATT_DB IPRA,STD_PROFILE STD WHERE
    PP.oid= PP_OID
    AND  PP.PART_TYPE IN (16,19,21,24)
    AND IPRA.INP_PART_OID = PP.OID
    AND IPRA.STD_PROFILE_OID=STD.OID
    union all
    select   SPL.STORAGE_CODE from PRD_PART PP, INP_LC_ATT_DB IPRA ,STD_PROFILE PROF, STD_PLATE SPL  WHERE
    PP.oid= PP_OID
    AND  PP.PART_TYPE IN (17)
    AND IPRA.INP_PART_OID = PP.OID
    AND PROF.OID=IPRA.STD_SECTION_OID
    AND (SPL.MATERIAL_OID=PROF.MATERIAL_OID
    AND SPL.THICKNESS=IPRA.PL_THICK_VALUE*1000)
    )     as STOCKCODE

    from
    (
        select
        PP.OID as PP_OID,
        PEP.OID as EXPL_OID,
        get_block_code(PP.BLOCK_OID) as BLOCK,
        PP.CODE,
        PP.PART_TYPE,
        BSN.DESCRIPTION,
        BSN.PARENT_NODE,
        BSN.ATOM_TYPE,
        BNT.ORDINAL,
        BNT.ATOM_TYPE as TYPE_ATOM_TYPE,
        BNT.SYMBOL,
        PEP.WEIGHT,
        PEP.X_COG,
        PEP.Y_COG,
        PEP.Z_COG,
        RPT_GET_PART_LENGTH(PP.OID)*1000 as PRF_LENGTH,
        (select NAME from BS_NODE where OID=BSN.PARENT_NODE) as LINE_NAME,
        (select NAME from BS_NODE_TYPE where OID= (select BS_NODE_TYPE_OID from BS_NODE where OID=BSN.PARENT_NODE) ) as LINE_TYPE,
        (select DESCRIPTION from BS_NODE_TYPE where OID= (select BS_NODE_TYPE_OID from BS_NODE where OID=BSN.PARENT_NODE) ) as LINE_TYPE_DESCRIPTION,
        bs_node_adn_from_oid(BSN.OID) BS_ADN
        from BS_NODE BSN ,BS_NODE_TYPE BNT,BS_ATOM_FIXED_ATTRIBUTE  AFA,BS_DESIGN_ATOM BDA, BS_DESIGN_NODE BDN, PRD_EXPL_PART PEP ,PRD_PART PP
        where
         BSN.BS_NODE_TYPE_OID=BNT.OID
        AND BSN.OID = AFA.BS_NODE_OID
        AND AFA.BS_DS_ATOM_OID = BDA.OID
        AND BDA.BS_DESIGN_NODE_OID = BDN.OID
        AND PEP.OID=BDN.MODEL_OID
        AND PEP.PRD_PART_OID=PP.OID
        AND BSN.ATOM_TYPE=3
        AND (SELECT DESCRIPTION FROM BLOCK WHERE OID = PP.BLOCK_OID) LIKE '%' || :docNumber || '%'
    )