SELECT
    PLS.*,
    SYS.*,
    CMP.*,
    ELE.*,
    ZON.USERID AS ZONEUSERID,
    SPL.USERID AS SPOOL,
    ISO.USERID AS ISOM,
    CMP.NAME AS CMPNAME
FROM
    PLS_ELEM PLS
        LEFT JOIN SYSTEMS SYS ON SYS.SEQID = PLS.SYSTEM
        LEFT JOIN ZONE ZON ON ZON.SEQID = PLS.ZONE
        LEFT JOIN SPOOL SPL ON SPL.ID = PLS.SPOOLID AND SPL.ZONE = PLS.ZONE AND SPL.SYSTEM = PLS.SYSTEM
        LEFT JOIN ISOMETRIC ISO ON ISO.ID = PLS.ISOMID AND ISO.ZONE = PLS.ZONE
        LEFT JOIN HVACCMP_COMPONENT CMP ON CMP.OID = PLS.CMP_OID
        LEFT JOIN ELEMENT_LANG ELE ON ELE.ELEM = PLS.OID
WHERE SYS.NAME LIKE '&system' AND PLS.SPOOLID IS NOT NULL
