SELECT
    PRDPLATE.PRD_PART_OID AS PARTOID,
    STDMAT.CODE AS MATERIAL,
    PRDPLATE.MATERIAL_OID AS MATERIAL_OID,
    PRDPLATE.THICKNESS AS THICK
FROM
    PRD_PLATE_ATT PRDPLATE,
    MATERIAL STDMAT
WHERE
        PRDPLATE.PRD_PART_OID IN (&plateOids) AND
        PRDPLATE.MATERIAL_OID = STDMAT.OID
UNION ALL
SELECT
    INPPLATE.INP_PART_OID AS PARTOID,
    STDMAT.CODE AS MATERIAL,
    INPPLATE.MATERIAL_OID AS MATERIAL_OID,
    INPPLATE.THICKNESS * 1000 AS THICK
FROM
    INP_PLATE_ATT_DB INPPLATE,
    MATERIAL STDMAT
WHERE
        INPPLATE.INP_PART_OID IN (&plateOids) AND
        INPPLATE.MATERIAL_OID = STDMAT.OID
UNION ALL
SELECT
    ASPLATE.OID AS PARTOID,
    ASPLATE.MATQ AS MATERIAL,
    MATT.OID AS MATERIAL_OID,
    ASPLATE.THICKNESS AS THICK
FROM
    AS_STD_PART_PLATE ASPLATE,
    MATERIAL MATT
WHERE
        ASPLATE.OID IN (&plateOids) AND
        MATT.CODE = ASPLATE.MATQ
UNION ALL
SELECT
    ASCONTPLATE.OID AS PARTOID,
    ASCONTPLATE.MATQ AS MATERIAL,
    MATT.OID AS MATERIAL_OID,
    ASCONTPLATE.THICKNESS AS THICK
FROM
    AS_PART_CONT_PLATE ASCONTPLATE,
    MATERIAL MATT
WHERE
        ASCONTPLATE.OID IN (&plateOids) AND
        MATT.CODE = ASCONTPLATE.MATQ