SELECT
    PRD.OID AS PARTOID,
    SP.OID as SPARTOID,
    PRD.CODE AS PARTNAME,
    SP.DESCRIPTION AS PARTDESCR,
    BLOCK.CODE AS BLOCKNAME,
    SP.WEIGHT AS WEIGHT,
    SP.AREA AS AREA,
    SP.THICK AS THICK,
    SP.KSE_OID AS KSE
FROM
    BLOCK BLOCK,
    PRD_PART PRD,
    INP_SINGLE_PART_DB SP
WHERE
    BLOCK.OID = PRD.BLOCK_OID AND
    SP.PRD_PART_OID = PRD.OID